version: '3.4'

services:
  api-gateway:
    build:
      context: ./ApiGateway
    ports:
      - "5000:80"
    depends_on:
      - user-service

  user-service:
    build:
      context: ./UserService
    ports:
      - "5001:80"
